# _config.yml
title: "Majid Niazkar"
description: "Hydrology • Climate Extremes • Hydroinformatics"
theme: jekyll-theme-minimal
logo: /assets/profile.jpg
show_downloads: false
google_scholar: "https://scholar.google.com/citations?user=j88TvigAAAAJ&hl=en&oi=ao"
orcid: "https://https://orcid.org/0000-0002-5022-1026"
